//
// This source file is a part of borsch.3d
//
// Copyright (C) borsch.3d team 2017-2018
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//

#ifndef _GLENUM_H_F2C8D7DD_3802_452C_AE7B_CCD9A2553F4B_
#define _GLENUM_H_F2C8D7DD_3802_452C_AE7B_CCD9A2553F4B_ 

enum GLenum {
  GL_FLOAT,
  GL_FLOAT_VEC2,
  GL_FLOAT_VEC3,
  GL_FLOAT_VEC4,
  GL_DOUBLE,
  GL_DOUBLE_VEC2,
  GL_DOUBLE_VEC3,
  GL_DOUBLE_VEC4,
  GL_INT,
  GL_INT_VEC2,
  GL_INT_VEC3,
  GL_INT_VEC4,
  GL_UNSIGNED_INT,
  GL_UNSIGNED_INT_VEC2,
  GL_UNSIGNED_INT_VEC3,
  GL_UNSIGNED_INT_VEC4,
  GL_BOOL,
  GL_BOOL_VEC2,
  GL_BOOL_VEC3,
  GL_BOOL_VEC4,
  GL_FLOAT_MAT2,
  GL_FLOAT_MAT3,
  GL_FLOAT_MAT4,
  GL_FLOAT_MAT2x3,
  GL_FLOAT_MAT2x4,
  GL_FLOAT_MAT3x2,
  GL_FLOAT_MAT3x4,
  GL_FLOAT_MAT4x2,
  GL_FLOAT_MAT4x3,
  GL_DOUBLE_MAT2,
  GL_DOUBLE_MAT3,
  GL_DOUBLE_MAT4,
  GL_DOUBLE_MAT2x3,
  GL_DOUBLE_MAT2x4,
  GL_DOUBLE_MAT3x2,
  GL_DOUBLE_MAT3x4,
  GL_DOUBLE_MAT4x2,
  GL_DOUBLE_MAT4x3,
  GL_SAMPLER_1D,
  GL_SAMPLER_2D,
  GL_SAMPLER_3D,
  GL_SAMPLER_CUBE,
  GL_SAMPLER_1D_SHADOW,
  GL_SAMPLER_2D_SHADOW,
  GL_SAMPLER_1D_ARRAY,
  GL_SAMPLER_2D_ARRAY,
  GL_SAMPLER_1D_ARRAY_SHADOW,
  GL_SAMPLER_2D_ARRAY_SHADOW,
  GL_SAMPLER_2D_MULTISAMPLE,
  GL_SAMPLER_2D_MULTISAMPLE_ARRAY,
  GL_SAMPLER_CUBE_SHADOW,
  GL_SAMPLER_BUFFER,
  GL_SAMPLER_2D_RECT,
  GL_SAMPLER_2D_RECT_SHADOW,
  GL_INT_SAMPLER_1D,
  GL_INT_SAMPLER_2D,
  GL_INT_SAMPLER_3D,
  GL_INT_SAMPLER_CUBE,
  GL_INT_SAMPLER_1D_ARRAY,
  GL_INT_SAMPLER_2D_ARRAY,
  GL_INT_SAMPLER_2D_MULTISAMPLE,
  GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY,
  GL_INT_SAMPLER_BUFFER,
  GL_INT_SAMPLER_2D_RECT,
  GL_UNSIGNED_INT_SAMPLER_1D,
  GL_UNSIGNED_INT_SAMPLER_2D,
  GL_UNSIGNED_INT_SAMPLER_3D,
  GL_UNSIGNED_INT_SAMPLER_CUBE,
  GL_UNSIGNED_INT_SAMPLER_1D_ARRAY,
  GL_UNSIGNED_INT_SAMPLER_2D_ARRAY,
  GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE,
  GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY,
  GL_UNSIGNED_INT_SAMPLER_BUFFER,
  GL_UNSIGNED_INT_SAMPLER_2D_RECT
};

#endif // _GLENUM_H_F2C8D7DD_3802_452C_AE7B_CCD9A2553F4B_
